sudo: false
language: python
python:
  - "3.6"
  - "3.7-dev"

install: pip install dataclasses requests toml pytest pytest-cov codecov 

cache: pip

script: PYTHONPATH=.:$PYTHONPATH pytest tests

after_success:
- codecov
