sudo: false
language: python
python:
  - "3.6"
  - "3.7"

install: pip install dataclasses requests tomli pytest pytest-cov codecov 

cache: pip

script: PYTHONPATH=.:$PYTHONPATH pytest --cov configclasses --cov-report=term-missing tests

after_success:
- codecov
